### ISSUE TITLE
How to do calculate simiarity score between query and gallery item without indexing

### ISSUE THREAD

**Issue by duyc168** [LinWeizheDragon/FLMR#15]
hi, I want to compare the retrieval results between with and without indexing, how to do calculate simiarity score between query and gallery item without indexing?

**Comment by LinWeizheDragon** [comment]
Hi, just to let you know that a finetuning script is now available at https://github.com/LinWeizheDragon/FLMR?tab=readme-ov-file#new-finetune-the-preflmr-model-on-downstream-datasets
