### ISSUE TITLE
作者你好，这个FLMR和官方版本的Retrieval-Augmented-Visual-Question-Answering区别在哪？FLMR是不是没用blip？

### ISSUE THREAD

**Issue by zzk2021** [LinWeizheDragon/FLMR#19]

**Comment by LinWeizheDragon** [comment]
This is also official. It is difficult to set up the entire environment with the original RA-VQA codebase. We provide an implementation based on Huggingface-transformers. This implementation provides support for inference with FLMR and PreFLMR, fine-tuning scripts, and evaluation scripts. You can easily run inference with this implementation.
If you want to fine-tune a blip based on the retrieved documents of PreFLMR, you can run inference, collect the retrieved documents, and write your own code to fine-tune a blip model.

**Comment by zzk2021** [comment]
thanks for your reply!
