### ISSUE TITLE
what is pos_item_ids and pos_item_contents mean?

### ISSUE THREAD

**Issue by zzk2021** [LinWeizheDragon/FLMR#21]
![image](https://github.com/LinWeizheDragon/FLMR/assets/73774678/ec560013-0aca-477d-9ea4-f59423e0d5dc)

**Comment by LinWeizheDragon** [comment]
`pos_item_ids` is the list of document ids (document indices in the corpus for retrieval). They are the ids of documents that are considered "relevant" to the query. They are typically the ground-truth annotations in those retrieval datasets.
`pos_item_contents` are just the content of these document ids. They are pre-extracted for convenience.
