### ISSUE TITLE
does this warning matter?  can not find the separator in the input_ids:

### ISSUE THREAD

**Issue by zzk2021** [LinWeizheDragon/FLMR#25]
![image](https://github.com/user-attachments/assets/55104c07-36d4-43a2-9fc4-ecae1ce65d15)

**Comment by LinWeizheDragon** [comment]
Yes, the; separator is important. The code Will automatically mask the latent representations of the instruction (before ;) When computing query-doc similarities. Please always input an instruction, a ;, and a question.

**Comment by zzk2021** [comment]
where is this separator added？
<img width="989" alt="image" src="https://github.com/user-attachments/assets/026f5459-03a6-4963-9a55-a8f380beeaf6">
I add ”;“ to the end of the sentence but it still warning

**Comment by LinWeizheDragon** [comment]
Ah sorry it is a :. A typo

**Comment by LinWeizheDragon** [comment]
You can find the relevant code in example_use_preflmr.py
The separator is added to the dataset's instruction column. So I may not explicitly add it to the question in the example file.
