### ISSUE TITLE
Wikipedia Corpus used for OK-VQA task

### ISSUE THREAD

**Issue by ShuaiWang97** [LinWeizheDragon/FLMR#31]
Thanks for the great work!
In paper FLMR, I saw there are two external datasets _Google Search Corpus_ and _Wikipedia Corpus_, used for OK-VQA task. I saw the Google Search Corpus [here](https://drive.google.com/drive/folders/15uWx33RY5UmR_ZmLO6Ve1wyzbXsLxV6o), but did not find Wikipedia Corpus. I am quite interested in the later one, so wanna ask can I find that data somewhere? Thanks in a dvance!

Best,
Shuai

**Comment by LinWeizheDragon** [comment]
https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR

It is released together with the M2KR benchmark. Check out the "OKVQA_data" and "OKVQA_passages".

**Comment by ShuaiWang97** [comment]
Thank you very much for the prompt response. 
I have another question about the example given in the README about example_use_preflmr.py.
![image](https://github.com/user-attachments/assets/2aa69191-35d8-4e81-b788-79bd7f799b2d)


After downloading the `--image_root_dir` data from [here ](https://huggingface.co/datasets/BByrneLab/RAVQAV2Data/tree/main), the --dataset_path from [here ](https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR/tree/main/OKVQA_data) and --passage_dataset_path from [here](https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR/tree/main/OKVQA_passages), I got the error of `KeyError: 'ROIs'` from line of code `ds = ds.map(add_path_prefix_in_img_path, fn_kwargs={"prefix": args.image_root_dir})` and when I checked the dataset(showed below) it seems like there is indeed no key of "ROIs". Can you please give me some hints of this error? Thanks in advance!
![image](https://github.com/user-attachments/assets/04655046-8da4-401b-8d07-1414c12c531d)

**Comment by LinWeizheDragon** [comment]
It seems that we did not incorporate ROIs into the wiki-version of OKVQA. You can merge the ROIs column from [here](https://huggingface.co/datasets/BByrneLab/OKVQA_FLMR_preprocessed_data). It contains pre-extracted ROI features.

**Comment by ShuaiWang97** [comment]
Thanks for the quick answer! I have incorporated the ROI and now the dataset seems to be working.

I am sorry i need to ask another question in the line 75 `query_embeddings = flmr_model.query(**query_input).late_interaction_output` of [example_use_flmr.py](https://github.com/LinWeizheDragon/FLMR/blob/main/examples/example_use_flmr.py). This line of code is using [modelling_flmr.py](https://github.com/LinWeizheDragon/FLMR/blob/9df9fa3731eb3f0770233949b8ff2b37ada96d90/flmr/models/flmr/modeling_flmr.py#L636) line 1152 `transformer_mapping_outputs = self.transformer_mapping_network()`, and I got error of     

![image](https://github.com/user-attachments/assets/b4c9af6b-3b8c-426b-a29b-c5fa9b422eda)

Seems like the error is becasue of [line 1118](https://github.com/LinWeizheDragon/FLMR/blob/9df9fa3731eb3f0770233949b8ff2b37ada96d90/flmr/models/flmr/modeling_flmr.py#L1118) `pixel_values = pixel_values.reshape(
                        -1, pixel_values.shape[2], pixel_values.shape[3], pixel_values.shape[4]
                    )` that the first diemention is expanded by ten times. Then variable `transformer_mapping_input_features`'s zero diemension does not match others.

Do you have any suggestions on solving this error? Thanks!

Best,
Shuai

**Comment by LinWeizheDragon** [comment]
Hi, FLMR doesn't have the transformer mapping structure - this line should not be called. Could you please confirm that you are using FLMR [here](https://huggingface.co/LinWeizheDragon/FLMR) instead of PreFLMR?

PreFLMR, which was a follow-up work of FLMR, doesn't use multiple ROIs (instead, it uses a mapping transformer to take patch-level embeddings) in training due to the limited computation available.

**Comment by ShuaiWang97** [comment]
Clear! Thank you for the help:)

**Comment by mxw20010804** [comment]
> https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR
> 
> It is released together with the M2KR benchmark. Check out the "OKVQA_data" and "OKVQA_passages".

@LinWeizheDragon Does OKVQA_passages contains all Google Search Corpus and Wikipedia Corpus ?

**Comment by mxw20010804** [comment]
> Clear! Thank you for the help:)

@ShuaiWang97 sorry to bother you. do you know do OKVQA_passages contains both Google Search Corpus and Wikipedia Corpus ?

**Comment by LinWeizheDragon** [comment]
> > https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR
> > 
> > It is released together with the M2KR benchmark. Check out the "OKVQA_data" and "OKVQA_passages".
> 
> @LinWeizheDragon Does OKVQA_passages contains all Google Search Corpus and Wikipedia Corpus ?

I think this one contains only Wikipedia passages. 

You can find the GS data in

https://huggingface.co/datasets/BByrneLab/OKVQA_FLMR_preprocessed_GoogleSearch_passages

https://huggingface.co/datasets/BByrneLab/OKVQA_FLMR_preprocessed_data

**Comment by mxw20010804** [comment]
> > > https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR
> > > It is released together with the M2KR benchmark. Check out the "OKVQA_data" and "OKVQA_passages".
> > 
> > 
> > [@LinWeizheDragon](https://github.com/LinWeizheDragon) Does OKVQA_passages contains all Google Search Corpus and Wikipedia Corpus ?
> 
> I think this one contains only Wikipedia passages.
> 
> You can find the GS data in
> 
> https://huggingface.co/datasets/BByrneLab/OKVQA_FLMR_preprocessed_GoogleSearch_passages
> 
> https://huggingface.co/datasets/BByrneLab/OKVQA_FLMR_preprocessed_data

OK, thank you for your help!
