### ISSUE TITLE
Something about evaluate

### ISSUE THREAD

**Issue by lzhptr** [LinWeizheDragon/FLMR#33]
What does the Ks parameter mean? Why does the documentation say "Enable --Ks 1 5 10 20 50 100 500: max(Ks) needs to be 500 to match the performance reported in the PreFLMR paper"

**Comment by LinWeizheDragon** [comment]
Despite being closed, I'd respond to this question for other audiences. The engine chooses some hyperparameters (e.g. threshold for centroid search) based on the max Ks, in this case, 500. If max(Ks) = 100, the result is slightly worse than what was reported in the paper.

**Comment by lzhptr** [comment]
> Despite being closed, I'd respond to this question for other audiences. The engine chooses some hyperparameters (e.g. threshold for centroid search) based on the max Ks, in this case, 500. If max(Ks) = 100, the result is slightly worse than what was reported in the paper.

Thank you very much!
