### ISSUE TITLE
definition of load_dataset

### ISSUE THREAD

**Issue by duyc168** [LinWeizheDragon/FLMR#8]
hello, it seems that in examples/example_use_flmr.py, the load_dataset is not defined, and other files do not include load_dataset either. anything missing during uploading? thanks
![4F422D73-7173-4E04-A619-2BCF67D0128B](https://github.com/LinWeizheDragon/FLMR/assets/74500098/833abf45-4068-4196-809b-2c2b758af405)

**Comment by LinWeizheDragon** [comment]
This is an internal function from huggingface datasets. Simply `pip install datasets` and you will have this function.

**Comment by duyc168** [comment]
ok, I misunderstand😂 thank you
